/*
 * ASM3D - a3_shaders.c
 * GLSL 330 sources (backend adds #version). Attribute locations:
 *   0 position, 1 normal, 2 uv, 3 color, 4-7 instance model matrix,
 *   8 instance color, 9 instance params (metallic, roughness, emissive, receive_shadows)
 */
#include "a3_shaders.h"

const char *A3_SHADER_LIT_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=1) in vec3 a_normal;\n"
    "layout(location=2) in vec2 a_uv;\n"
    "layout(location=4) in vec4 i_m0;\n"
    "layout(location=5) in vec4 i_m1;\n"
    "layout(location=6) in vec4 i_m2;\n"
    "layout(location=7) in vec4 i_m3;\n"
    "layout(location=8) in vec4 i_color;\n"
    "layout(location=9) in vec4 i_params;\n"
    "uniform mat4 u_view_proj;\n"
    "uniform mat4 u_light_view_proj;\n"
    "out vec3 v_world_pos;\n"
    "out vec3 v_normal;\n"
    "out vec2 v_uv;\n"
    "out vec4 v_color;\n"
    "out vec4 v_params;\n"
    "out vec4 v_shadow_pos;\n"
    "out vec3 v_local_pos;\n"
    "void main() {\n"
    "    mat4 model = mat4(i_m0, i_m1, i_m2, i_m3);\n"
    "    vec4 wp = model * vec4(a_position, 1.0);\n"
    "    mat3 m = mat3(model);\n"
    "    mat3 normal_matrix = mat3(cross(m[1], m[2]), cross(m[2], m[0]), cross(m[0], m[1]));\n"
    "    v_world_pos = wp.xyz;\n"
    "    v_normal = normalize(normal_matrix * a_normal);\n"
    "    v_uv = a_uv;\n"
    "    v_color = i_color;\n"
    "    v_params = i_params;\n"
    "    v_shadow_pos = u_light_view_proj * wp;\n"
    "    v_local_pos = a_position;\n"
    "    gl_Position = u_view_proj * wp;\n"
    "}\n";

const char *A3_SHADER_LIT_FS_HEAD =
    "in vec3 v_world_pos;\n"
    "in vec3 v_normal;\n"
    "in vec2 v_uv;\n"
    "in vec4 v_color;\n"
    "in vec4 v_params;\n"
    "in vec4 v_shadow_pos;\n"
    "in vec3 v_local_pos;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_albedo_tex;\n"
    "uniform int u_has_texture;\n"
    "uniform sampler2DShadow u_shadow_map;\n"
    "uniform int u_shadows_enabled;\n"
    "uniform vec2 u_shadow_texel;\n"
    "uniform vec3 u_camera_pos;\n"
    "uniform float u_time;\n"
    "uniform vec3 u_sun_dir;\n"          /* direction the light travels */
    "uniform vec3 u_sun_color;\n"
    "uniform vec3 u_sky_color;\n"
    "uniform vec3 u_ground_color;\n"
    "uniform float u_ambient;\n"
    "uniform vec3 u_fog_color;\n"
    "uniform float u_fog_density;\n"
    "#define A3_MAX_LIGHTS 16\n"
    "uniform int u_light_count;\n"
    "uniform vec4 u_light_pos[A3_MAX_LIGHTS];\n"     /* xyz position, w range */
    "uniform vec4 u_light_color[A3_MAX_LIGHTS];\n"   /* rgb * intensity, w type (1 point, 2 spot) */
    "uniform vec4 u_light_dir[A3_MAX_LIGHTS];\n"     /* xyz spot direction, w cos(outer half angle) */
    "uniform vec4 u_material[4];\n"                  /* custom material parameters (Shader Maker) */
    "uniform sampler2D u_tex1;\n"
    "uniform sampler2D u_tex2;\n"
    "const float PI = 3.14159265;\n"
    "struct A3Surface {\n"
    "    vec3 albedo; float alpha; vec3 normal; float metallic; float roughness; vec3 emissive; float occlusion;\n"
    "    vec2 uv; vec4 color; vec3 world_pos; vec3 local_pos; vec3 view_dir; float time;\n"
    "};\n"
    "vec3 a3_hash3(vec3 p) { p = fract(p * vec3(443.897, 441.423, 437.195)); p += dot(p, p.yxz + 19.19); return fract((p.xxy + p.yxx) * p.zyx); }\n"
    "float a3_noise(vec3 p) {\n"
    "    vec3 i = floor(p); vec3 f = fract(p); f = f * f * (3.0 - 2.0 * f);\n"
    "    float n000 = a3_hash3(i).x, n100 = a3_hash3(i + vec3(1,0,0)).x, n010 = a3_hash3(i + vec3(0,1,0)).x, n110 = a3_hash3(i + vec3(1,1,0)).x;\n"
    "    float n001 = a3_hash3(i + vec3(0,0,1)).x, n101 = a3_hash3(i + vec3(1,0,1)).x, n011 = a3_hash3(i + vec3(0,1,1)).x, n111 = a3_hash3(i + vec3(1,1,1)).x;\n"
    "    return mix(mix(mix(n000, n100, f.x), mix(n010, n110, f.x), f.y), mix(mix(n001, n101, f.x), mix(n011, n111, f.x), f.y), f.z);\n"
    "}\n"
    "float a3_fbm(vec3 p) { float s = 0.0, a = 0.5; for (int i = 0; i < 5; ++i) { s += a * a3_noise(p); p *= 2.02; a *= 0.5; } return s; }\n"
    "/* ---- surface function (default or generated by the Shader Maker) ---- */\n";

const char *A3_SHADER_DEFAULT_SURFACE =
    "void a3_surface(inout A3Surface s) {\n"
    "    vec3 base = s.color.rgb;\n"
    "    if (u_has_texture != 0) { vec4 t = texture(u_albedo_tex, s.uv); base *= t.rgb; s.alpha *= t.a; }\n"
    "    s.albedo = base;\n"
    "}\n";

const char *A3_SHADER_LIT_FS_TAIL =
    "/* ---- lighting ---- */\n"
    "float a3_distribution_ggx(float ndh, float r) { float a = r * r; float a2 = a * a; float d = ndh * ndh * (a2 - 1.0) + 1.0; return a2 / (PI * d * d + 1e-6); }\n"
    "float a3_geometry(float ndv, float ndl, float r) { float k = (r + 1.0); k = k * k / 8.0; return (ndv / (ndv * (1.0 - k) + k)) * (ndl / (ndl * (1.0 - k) + k)); }\n"
    "vec3 a3_fresnel(float c, vec3 f0) { return f0 + (1.0 - f0) * pow(1.0 - c, 5.0); }\n"
    "vec3 a3_brdf(A3Surface s, vec3 l, vec3 radiance) {\n"
    "    vec3 n = s.normal, v = s.view_dir, h = normalize(l + v);\n"
    "    float ndl = max(dot(n, l), 0.0); if (ndl <= 0.0) return vec3(0.0);\n"
    "    float ndv = max(dot(n, v), 1e-4), ndh = max(dot(n, h), 0.0);\n"
    "    float r = clamp(s.roughness, 0.04, 1.0);\n"
    "    vec3 f0 = mix(vec3(0.04), s.albedo, s.metallic);\n"
    "    vec3 f = a3_fresnel(max(dot(h, v), 0.0), f0);\n"
    "    vec3 spec = a3_distribution_ggx(ndh, r) * a3_geometry(ndv, ndl, r) * f / (4.0 * ndv * ndl + 1e-4);\n"
    "    vec3 kd = (1.0 - f) * (1.0 - s.metallic);\n"
    "    return (kd * s.albedo / PI + spec) * radiance * ndl;\n"
    "}\n"
    "float a3_shadow(vec3 n) {\n"
    "    if (u_shadows_enabled == 0 || v_params.w < 0.5) return 1.0;\n"
    "    vec3 p = v_shadow_pos.xyz / v_shadow_pos.w * 0.5 + 0.5;\n"
    "    if (p.z > 1.0 || p.x < 0.0 || p.x > 1.0 || p.y < 0.0 || p.y > 1.0) return 1.0;\n"
    "    float bias = 0.0015 + 0.003 * (1.0 - clamp(dot(n, -u_sun_dir), 0.0, 1.0));\n"
    "    float sum = 0.0;\n"
    "    for (int y = -1; y <= 1; ++y) for (int x = -1; x <= 1; ++x)\n"
    "        sum += texture(u_shadow_map, vec3(p.xy + vec2(x, y) * u_shadow_texel, p.z - bias));\n"
    "    return sum / 9.0;\n"
    "}\n"
    "void main() {\n"
    "    A3Surface s;\n"
    "    s.color = v_color; s.uv = v_uv; s.world_pos = v_world_pos; s.local_pos = v_local_pos; s.time = u_time;\n"
    "    s.view_dir = normalize(u_camera_pos - v_world_pos);\n"
    "    s.normal = normalize(gl_FrontFacing ? v_normal : -v_normal);\n"
    "    s.albedo = v_color.rgb; s.alpha = v_color.a; s.metallic = v_params.x; s.roughness = v_params.y;\n"
    "    s.emissive = vec3(0.0); s.occlusion = 1.0;\n"
    "    a3_surface(s);\n"
    "    s.normal = normalize(s.normal);\n"
    "    vec3 color = vec3(0.0);\n"
    "    /* sun */\n"
    "    color += a3_brdf(s, -u_sun_dir, u_sun_color) * a3_shadow(s.normal);\n"
    "    /* local lights */\n"
    "    for (int i = 0; i < u_light_count; ++i) {\n"
    "        vec3 lv = u_light_pos[i].xyz - s.world_pos; float d = length(lv); vec3 l = lv / max(d, 1e-4);\n"
    "        float range = u_light_pos[i].w;\n"
    "        float att = clamp(1.0 - pow(d / range, 4.0), 0.0, 1.0); att = att * att / (d * d + 1.0);\n"
    "        if (u_light_color[i].w > 1.5) {\n"
    "            float c = dot(-l, u_light_dir[i].xyz); float outer = u_light_dir[i].w;\n"
    "            att *= smoothstep(outer, mix(outer, 1.0, 0.25), c);\n"
    "        }\n"
    "        color += a3_brdf(s, l, u_light_color[i].rgb * att);\n"
    "    }\n"
    "    /* hemispheric ambient */\n"
    "    float up = s.normal.y * 0.5 + 0.5;\n"
    "    vec3 amb = mix(u_ground_color, u_sky_color, up) * u_ambient;\n"
    "    vec3 f0a = mix(vec3(0.04), s.albedo, s.metallic);\n"
    "    float ndv_a = max(dot(s.normal, s.view_dir), 1e-4);\n"
    "    vec3 fa = f0a + (max(vec3(1.0 - s.roughness), f0a) - f0a) * pow(1.0 - ndv_a, 5.0);\n"
    "    vec3 refl = reflect(-s.view_dir, s.normal);\n"
    "    vec3 env = mix(u_ground_color, u_sky_color, smoothstep(-0.2, 0.4, refl.y)) * u_ambient * 2.0;\n"
    "    color += (amb * s.albedo * (1.0 - fa) * (1.0 - s.metallic) + env * fa * (1.0 - s.roughness * 0.6)) * s.occlusion;\n"
    "    color += s.emissive + s.albedo * v_params.z;\n"
    "    /* fog */\n"
    "    float dist = length(u_camera_pos - s.world_pos);\n"
    "    float fog = 1.0 - exp(-u_fog_density * dist);\n"
    "    color = mix(color, u_fog_color, clamp(fog, 0.0, 1.0));\n"
    "    o_color = vec4(color, s.alpha);\n"
    "}\n";

int a3_shader_surface_line_offset(void) {
    int lines = 0;
    for (const char *p = A3_SHADER_LIT_FS_HEAD; *p; ++p) if (*p == '\n') ++lines;
    return lines;
}

const char *A3_SHADER_SHADOW_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=4) in vec4 i_m0;\n"
    "layout(location=5) in vec4 i_m1;\n"
    "layout(location=6) in vec4 i_m2;\n"
    "layout(location=7) in vec4 i_m3;\n"
    "uniform mat4 u_view_proj;\n"
    "void main() { gl_Position = u_view_proj * mat4(i_m0, i_m1, i_m2, i_m3) * vec4(a_position, 1.0); }\n";

const char *A3_SHADER_SHADOW_FS =
    "void main() {}\n";

const char *A3_SHADER_FULLSCREEN_VS =
    "out vec2 v_uv;\n"
    "void main() {\n"
    "    vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);\n"
    "    v_uv = p;\n"
    "    gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);\n"
    "}\n";

const char *A3_SHADER_SKY_VS =
    "out vec2 v_ndc;\n"
    "void main() {\n"
    "    vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);\n"
    "    v_ndc = p * 2.0 - 1.0;\n"
    "    gl_Position = vec4(v_ndc, 1.0, 1.0);\n"
    "}\n";

const char *A3_SHADER_SKY_FS =
    "in vec2 v_ndc;\n"
    "out vec4 o_color;\n"
    "uniform mat4 u_inv_view_proj;\n"
    "uniform vec3 u_camera_pos;\n"
    "uniform vec3 u_sky_top;\n"
    "uniform vec3 u_sky_horizon;\n"
    "uniform vec3 u_ground_color;\n"
    "uniform vec3 u_sun_dir;\n"
    "uniform vec3 u_sun_color;\n"
    "uniform float u_time;\n"
    "void main() {\n"
    "    vec4 far = u_inv_view_proj * vec4(v_ndc, 1.0, 1.0);\n"
    "    vec3 dir = normalize(far.xyz / far.w - u_camera_pos);\n"
    "    float h = dir.y;\n"
    "    vec3 sky = mix(u_sky_horizon, u_sky_top, pow(clamp(h, 0.0, 1.0), 0.45));\n"
    "    vec3 ground = mix(u_sky_horizon, u_ground_color, clamp(-h * 4.0, 0.0, 1.0));\n"
    "    vec3 col = h >= 0.0 ? sky : ground;\n"
    "    vec3 to_sun = -u_sun_dir;\n"
    "    float sd = max(dot(dir, to_sun), 0.0);\n"
    "    col += u_sun_color * (pow(sd, 900.0) * 6.0 + pow(sd, 12.0) * 0.12) * step(-0.05, h);\n"
    "    o_color = vec4(col, 1.0);\n"
    "}\n";

const char *A3_SHADER_TONEMAP_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_hdr;\n"
    "uniform float u_exposure;\n"
    "uniform float u_vignette;\n"
    "vec3 aces(vec3 x) { return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0); }\n"
    "void main() {\n"
    "    vec3 c = texture(u_hdr, v_uv).rgb * u_exposure;\n"
    "    c = aces(c);\n"
    "    c = pow(c, vec3(1.0 / 2.2));\n"
    "    vec2 d = v_uv - 0.5;\n"
    "    c *= 1.0 - u_vignette * dot(d, d) * 1.6;\n"
    "    o_color = vec4(c, dot(c, vec3(0.299, 0.587, 0.114)));\n" /* luma in alpha for FXAA */
    "}\n";

/* FXAA (quality-lite): edge-directed blur using luma stored in alpha. */
const char *A3_SHADER_FXAA_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_ldr;\n"
    "uniform vec2 u_texel;\n"
    "void main() {\n"
    "    float lm = texture(u_ldr, v_uv).a;\n"
    "    float ln = texture(u_ldr, v_uv + vec2(0.0, u_texel.y)).a;\n"
    "    float ls = texture(u_ldr, v_uv - vec2(0.0, u_texel.y)).a;\n"
    "    float le = texture(u_ldr, v_uv + vec2(u_texel.x, 0.0)).a;\n"
    "    float lw = texture(u_ldr, v_uv - vec2(u_texel.x, 0.0)).a;\n"
    "    float mn = min(lm, min(min(ln, ls), min(le, lw))), mx = max(lm, max(max(ln, ls), max(le, lw)));\n"
    "    vec3 c = texture(u_ldr, v_uv).rgb;\n"
    "    if (mx - mn < max(0.0312, mx * 0.125)) { o_color = vec4(c, 1.0); return; }\n"
    "    vec2 dir = normalize(vec2(ln - ls, lw - le) + 1e-5) * u_texel;\n"
    "    vec3 a = 0.5 * (texture(u_ldr, v_uv + dir * (1.0/3.0 - 0.5)).rgb + texture(u_ldr, v_uv + dir * (2.0/3.0 - 0.5)).rgb);\n"
    "    vec3 b = a * 0.5 + 0.25 * (texture(u_ldr, v_uv - dir * 0.5).rgb + texture(u_ldr, v_uv + dir * 0.5).rgb);\n"
    "    float lb = dot(b, vec3(0.299, 0.587, 0.114));\n"
    "    o_color = vec4((lb < mn || lb > mx) ? a : b, 1.0);\n"
    "}\n";

const char *A3_SHADER_LINES_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=3) in vec4 a_color;\n"
    "uniform mat4 u_view_proj;\n"
    "out vec4 v_color;\n"
    "void main() { v_color = a_color; gl_Position = u_view_proj * vec4(a_position, 1.0); }\n";

const char *A3_SHADER_LINES_FS =
    "in vec4 v_color;\n"
    "out vec4 o_color;\n"
    "void main() { o_color = v_color; }\n";

/* 2D UI: position in pixels, uv, color. u_mode: 0 = texture rgba, 1 = alpha (font atlas). */
const char *A3_SHADER_UI_VS =
    "layout(location=0) in vec2 a_position;\n"
    "layout(location=2) in vec2 a_uv;\n"
    "layout(location=3) in vec4 a_color;\n"
    "uniform vec2 u_screen;\n"
    "out vec2 v_uv;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    v_uv = a_uv; v_color = a_color;\n"
    "    gl_Position = vec4(a_position.x / u_screen.x * 2.0 - 1.0, 1.0 - a_position.y / u_screen.y * 2.0, 0.0, 1.0);\n"
    "}\n";

const char *A3_SHADER_UI_FS =
    "in vec2 v_uv;\n"
    "in vec4 v_color;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_tex;\n"
    "uniform int u_mode;\n"
    "void main() {\n"
    "    vec4 t = texture(u_tex, v_uv);\n"
    "    if (u_mode == 1) o_color = vec4(v_color.rgb, v_color.a * t.r);\n"
    "    else o_color = v_color * t;\n"
    "}\n";

/* Editor ground grid, drawn as a large quad with analytic anti-aliased lines. */
const char *A3_SHADER_GRID_VS =
    "layout(location=0) in vec3 a_position;\n"
    "uniform mat4 u_view_proj;\n"
    "uniform vec3 u_camera_pos;\n"
    "out vec3 v_world;\n"
    "void main() {\n"
    "    vec3 p = a_position * 500.0 + vec3(u_camera_pos.x, 0.0, u_camera_pos.z);\n"
    "    v_world = p;\n"
    "    gl_Position = u_view_proj * vec4(p, 1.0);\n"
    "}\n";

const char *A3_SHADER_GRID_FS =
    "in vec3 v_world;\n"
    "out vec4 o_color;\n"
    "uniform vec3 u_camera_pos;\n"
    "float grid(vec2 p, float scale) {\n"
    "    vec2 c = p / scale; vec2 d = fwidth(c);\n"
    "    vec2 g = abs(fract(c - 0.5) - 0.5) / d;\n"
    "    return 1.0 - min(min(g.x, g.y), 1.0);\n"
    "}\n"
    "void main() {\n"
    "    float dist = length(v_world.xz - u_camera_pos.xz);\n"
    "    float fade = 1.0 - smoothstep(30.0, 180.0, dist);\n"
    "    float g1 = grid(v_world.xz, 1.0) * 0.35, g10 = grid(v_world.xz, 10.0) * 0.6;\n"
    "    float a = max(g1, g10) * fade;\n"
    "    vec3 col = vec3(0.55);\n"
    "    if (abs(v_world.z) < fwidth(v_world.z) * 1.5) { col = vec3(0.9, 0.25, 0.25); a = fade; }\n"
    "    if (abs(v_world.x) < fwidth(v_world.x) * 1.5) { col = vec3(0.25, 0.45, 0.95); a = fade; }\n"
    "    if (a < 0.01) discard;\n"
    "    o_color = vec4(col, a);\n"
    "}\n";

/* Camera-facing particles: per-instance position/size (loc 4), color (loc 8). */
const char *A3_SHADER_PARTICLE_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=2) in vec2 a_uv;\n"
    "layout(location=4) in vec4 i_pos_size;\n"
    "layout(location=8) in vec4 i_color;\n"
    "uniform mat4 u_view_proj;\n"
    "uniform vec3 u_cam_right;\n"
    "uniform vec3 u_cam_up;\n"
    "out vec2 v_uv;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec3 p = i_pos_size.xyz + (u_cam_right * a_position.x + u_cam_up * a_position.y) * i_pos_size.w;\n"
    "    v_uv = a_uv; v_color = i_color;\n"
    "    gl_Position = u_view_proj * vec4(p, 1.0);\n"
    "}\n";

const char *A3_SHADER_PARTICLE_FS =
    "in vec2 v_uv;\n"
    "in vec4 v_color;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_tex;\n"
    "uniform int u_has_texture;\n"
    "void main() {\n"
    "    vec2 d = v_uv * 2.0 - 1.0;\n"
    "    float soft = clamp(1.0 - dot(d, d), 0.0, 1.0);\n"
    "    vec4 c = v_color;\n"
    "    if (u_has_texture != 0) c *= texture(u_tex, v_uv); else c.a *= soft * soft;\n"
    "    if (c.a < 0.003) discard;\n"
    "    o_color = c;\n"
    "}\n";
