/*
 * ASM3D - a3_shaders.c
 * GLSL 330 sources (backend adds #version). Attribute locations:
 *   0 position, 1 normal, 2 uv, 3 color, 4-7 instance model matrix,
 *   8 instance color, 9 instance params (metallic, roughness, emissive, receive_shadows)
 */
#include "a3_shaders.h"

const char *A3_SHADER_LIT_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=1) in vec3 a_normal;\n"
    "layout(location=2) in vec2 a_uv;\n"
    "layout(location=4) in vec4 i_m0;\n"
    "layout(location=5) in vec4 i_m1;\n"
    "layout(location=6) in vec4 i_m2;\n"
    "layout(location=7) in vec4 i_m3;\n"
    "layout(location=8) in vec4 i_color;\n"
    "layout(location=9) in vec4 i_params;\n"
    "layout(location=10) in vec4 i_lights0;\n"
    "layout(location=11) in vec4 i_lights1;\n"
    "uniform mat4 u_view_proj;\n"
    "uniform mat4 u_light_view_proj;\n"
    "flat out vec4 v_lights0;\n"
    "flat out vec4 v_lights1;\n"
    "out vec3 v_world_pos;\n"
    "out vec3 v_normal;\n"
    "out vec2 v_uv;\n"
    "out vec4 v_color;\n"
    "out vec4 v_params;\n"
    "out vec4 v_shadow_pos;\n"
    "out vec3 v_local_pos;\n"
    "void main() {\n"
    "    mat4 model = mat4(i_m0, i_m1, i_m2, i_m3);\n"
    "    vec4 wp = model * vec4(a_position, 1.0);\n"
    "    mat3 m = mat3(model);\n"
    "    mat3 normal_matrix = mat3(cross(m[1], m[2]), cross(m[2], m[0]), cross(m[0], m[1]));\n"
    "    v_world_pos = wp.xyz;\n"
    "    v_normal = normalize(normal_matrix * a_normal);\n"
    "    v_uv = a_uv;\n"
    "    v_color = i_color;\n"
    "    v_params = i_params;\n"
    "    v_shadow_pos = u_light_view_proj * wp;\n"
    "    v_local_pos = a_position;\n"
    "    v_lights0 = i_lights0;\n"
    "    v_lights1 = i_lights1;\n"
    "    gl_Position = u_view_proj * wp;\n"
    "}\n";

const char *A3_SHADER_LIT_FS_HEAD =
    "in vec3 v_world_pos;\n"
    "in vec3 v_normal;\n"
    "in vec2 v_uv;\n"
    "in vec4 v_color;\n"
    "in vec4 v_params;\n"
    "in vec4 v_shadow_pos;\n"
    "in vec3 v_local_pos;\n"
    "flat in vec4 v_lights0;\n"
    "flat in vec4 v_lights1;\n"
    "layout(location=0) out vec4 o_color;\n"
    "layout(location=1) out vec4 o_normal;\n"   /* world normal * 0.5 + 0.5, roughness (for SSAO / SSR) */
    "uniform sampler2D u_albedo_tex;\n"
    "uniform int u_has_texture;\n"
    "uniform sampler2DShadow u_shadow_map;\n"
    "uniform int u_shadows_enabled;\n"
    "uniform vec2 u_shadow_texel;\n"
    "uniform mat4 u_cascade_vp0;\n"
    "uniform mat4 u_cascade_vp1;\n"
    "uniform mat4 u_cascade_vp2;\n"
    "uniform vec3 u_cascade_split;\n"   /* far distance of each cascade (m) */
    "uniform vec3 u_cascade_texel;\n"   /* world size of one shadow texel per cascade */
    "uniform vec3 u_cascade_depth;\n"   /* 1 / depth range per cascade */
    "uniform vec3 u_camera_pos;\n"
    "uniform float u_time;\n"
    "uniform vec3 u_sun_dir;\n"          /* direction the light travels */
    "uniform vec3 u_sun_color;\n"
    "uniform vec3 u_sky_color;\n"
    "uniform vec3 u_sky_horizon;\n"
    "uniform vec3 u_ground_color;\n"
    "uniform float u_ambient;\n"
    "uniform vec3 u_fog_color;\n"
    "uniform float u_fog_density;\n"
    /* local lights: 256 per row, 3 texels each (position + range, color + type, spot direction + cos) */
    "uniform sampler2D u_light_tex;\n"
    "uniform int u_fog_in_post;\n"
    "uniform vec4 u_material[4];\n"                  /* custom material parameters (Shader Maker) */
    "uniform sampler2D u_tex1;\n"
    "uniform sampler2D u_tex2;\n"
    "const float PI = 3.14159265;\n"
    "struct A3Surface {\n"
    "    vec3 albedo; float alpha; vec3 normal; float metallic; float roughness; vec3 emissive; float occlusion;\n"
    "    vec2 uv; vec4 color; vec3 world_pos; vec3 local_pos; vec3 view_dir; float time;\n"
    "};\n"
    "vec3 a3_hash3(vec3 p) { p = fract(p * vec3(443.897, 441.423, 437.195)); p += dot(p, p.yxz + 19.19); return fract((p.xxy + p.yxx) * p.zyx); }\n"
    "float a3_noise(vec3 p) {\n"
    "    vec3 i = floor(p); vec3 f = fract(p); f = f * f * (3.0 - 2.0 * f);\n"
    "    float n000 = a3_hash3(i).x, n100 = a3_hash3(i + vec3(1,0,0)).x, n010 = a3_hash3(i + vec3(0,1,0)).x, n110 = a3_hash3(i + vec3(1,1,0)).x;\n"
    "    float n001 = a3_hash3(i + vec3(0,0,1)).x, n101 = a3_hash3(i + vec3(1,0,1)).x, n011 = a3_hash3(i + vec3(0,1,1)).x, n111 = a3_hash3(i + vec3(1,1,1)).x;\n"
    "    return mix(mix(mix(n000, n100, f.x), mix(n010, n110, f.x), f.y), mix(mix(n001, n101, f.x), mix(n011, n111, f.x), f.y), f.z);\n"
    "}\n"
    "float a3_fbm(vec3 p) { float s = 0.0, a = 0.5; for (int i = 0; i < 5; ++i) { s += a * a3_noise(p); p *= 2.02; a *= 0.5; } return s; }\n"
    /* bump mapping without tangents: h = surface height in meters at p (any
       procedural pattern); returns the perturbed normal. Fades with distance
       so fine detail does not sparkle far away. */
    "vec3 a3_bump(vec3 n, vec3 p, float h) {\n"
    "    vec3 dpx = dFdx(p), dpy = dFdy(p);\n"
    "    float dhx = dFdx(h), dhy = dFdy(h);\n"
    "    vec3 r1 = cross(dpy, n), r2 = cross(n, dpx);\n"
    "    float det = dot(dpx, r1);\n"
    "    if (abs(det) < 1e-12) return n;\n"
    "    vec3 grad = sign(det) * (dhx * r1 + dhy * r2);\n"
    "    float fade = 1.0 / (1.0 + length(u_camera_pos - p) * 0.04);\n"
    "    return normalize(abs(det) * n - grad * fade);\n"
    "}\n"
    "/* ---- surface function (default or generated by the Shader Maker) ---- */\n";

const char *A3_SHADER_DEFAULT_SURFACE =
    "void a3_surface(inout A3Surface s) {\n"
    "    vec3 base = s.color.rgb;\n"
    "    if (u_has_texture != 0) { vec4 t = texture(u_albedo_tex, s.uv); base *= t.rgb; s.alpha *= t.a; }\n"
    "    s.albedo = base;\n"
    "}\n";

const char *A3_SHADER_LIT_FS_TAIL =
    "/* ---- lighting ---- */\n"
    "float a3_distribution_ggx(float ndh, float r) { float a = r * r; float a2 = a * a; float d = ndh * ndh * (a2 - 1.0) + 1.0; return a2 / (PI * d * d + 1e-6); }\n"
    "float a3_geometry(float ndv, float ndl, float r) { float k = (r + 1.0); k = k * k / 8.0; return (ndv / (ndv * (1.0 - k) + k)) * (ndl / (ndl * (1.0 - k) + k)); }\n"
    "vec3 a3_fresnel(float c, vec3 f0) { return f0 + (1.0 - f0) * pow(clamp(1.0 - c, 0.0, 1.0), 5.0); }\n"
    "vec3 a3_brdf(A3Surface s, vec3 l, vec3 radiance) {\n"
    "    vec3 n = s.normal, v = s.view_dir, h = normalize(l + v);\n"
    "    float ndl = max(dot(n, l), 0.0); if (ndl <= 0.0) return vec3(0.0);\n"
    "    float ndv = max(dot(n, v), 1e-4), ndh = max(dot(n, h), 0.0);\n"
    "    float r = clamp(s.roughness, 0.04, 1.0);\n"
    "    vec3 f0 = mix(vec3(0.04), s.albedo, s.metallic);\n"
    "    vec3 f = a3_fresnel(max(dot(h, v), 0.0), f0);\n"
    "    vec3 spec = min(a3_distribution_ggx(ndh, r) * a3_geometry(ndv, ndl, r) * f / (4.0 * ndv * ndl + 1e-4), vec3(40.0));\n"
    "    vec3 kd = (1.0 - f) * (1.0 - s.metallic);\n"
    "    return (kd * s.albedo / PI + spec) * radiance * ndl;\n"
    "}\n"
    /* cascaded shadow maps: 3 tiles of a 2x2 atlas, picked by distance, normal offset + slope bias in meters */
    "float a3_shadow(vec3 n) {\n"
    "    if (u_shadows_enabled == 0 || v_params.w < 0.5) return 1.0;\n"
    "    float dist = length(u_camera_pos - v_world_pos);\n"
    "    if (dist > u_cascade_split.z) return 1.0;\n"
    "    int c = dist < u_cascade_split.x ? 0 : (dist < u_cascade_split.y ? 1 : 2);\n"
    "    mat4 m = c == 0 ? u_cascade_vp0 : (c == 1 ? u_cascade_vp1 : u_cascade_vp2);\n"
    "    float texel = c == 0 ? u_cascade_texel.x : (c == 1 ? u_cascade_texel.y : u_cascade_texel.z);\n"
    "    float dscale = c == 0 ? u_cascade_depth.x : (c == 1 ? u_cascade_depth.y : u_cascade_depth.z);\n"
    "    float ndl = clamp(dot(n, -u_sun_dir), 0.0, 1.0);\n"
    "    vec3 wp = v_world_pos + n * texel * (1.0 + 1.5 * (1.0 - ndl));\n"
    "    vec4 sp = m * vec4(wp, 1.0);\n"
    "    vec3 p = sp.xyz / sp.w * 0.5 + 0.5;\n"
    "    if (p.z > 1.0 || p.x < 0.0 || p.x > 1.0 || p.y < 0.0 || p.y > 1.0) return 1.0;\n"
    "    vec2 off = vec2(c == 1 ? 0.5 : 0.0, c == 2 ? 0.5 : 0.0);\n"
    "    vec2 lo = off + u_shadow_texel * 1.5, hi = off + vec2(0.5) - u_shadow_texel * 1.5;\n"
    "    vec2 uv = p.xy * 0.5 + off;\n"
    "    float bias = texel * (0.6 + 1.5 * (1.0 - ndl)) * dscale;\n"
    "    float sum = 0.0;\n"
    "    for (int y = -1; y <= 1; ++y) for (int x = -1; x <= 1; ++x)\n"
    "        sum += texture(u_shadow_map, vec3(clamp(uv + vec2(x, y) * u_shadow_texel, lo, hi), p.z - bias));\n"
    "    return mix(sum / 9.0, 1.0, smoothstep(u_cascade_split.z * 0.85, u_cascade_split.z, dist));\n"
    "}\n"
    "void main() {\n"
    "    A3Surface s;\n"
    "    s.color = v_color; s.uv = v_uv; s.world_pos = v_world_pos; s.local_pos = v_local_pos; s.time = u_time;\n"
    "    s.view_dir = normalize(u_camera_pos - v_world_pos);\n"
    "    s.normal = normalize(gl_FrontFacing ? v_normal : -v_normal);\n"
    "    s.albedo = v_color.rgb; s.alpha = v_color.a; s.metallic = v_params.x; s.roughness = v_params.y;\n"
    "    s.emissive = vec3(0.0); s.occlusion = 1.0;\n"
    "    a3_surface(s);\n"
    "    s.normal = normalize(s.normal);\n"
    "    vec3 color = vec3(0.0);\n"
    "    /* sun */\n"
    "    color += a3_brdf(s, -u_sun_dir, u_sun_color) * a3_shadow(s.normal);\n"
    "    /* local lights */\n"
    "    for (int k = 0; k < 8; ++k) {\n"
    "        float fi = k < 4 ? v_lights0[k] : v_lights1[k - 4];\n"
    "        if (fi < 0.0) break;\n"
    "        int li = int(fi + 0.5);\n"
    "        ivec2 base = ivec2((li % 256) * 3, li / 256);\n"
    "        vec4 lp = texelFetch(u_light_tex, base, 0);\n"
    "        vec4 lc = texelFetch(u_light_tex, base + ivec2(1, 0), 0);\n"
    "        vec3 lv = lp.xyz - s.world_pos; float d = length(lv); vec3 l = lv / max(d, 1e-4);\n"
    "        float range = lp.w;\n"
    "        float att = clamp(1.0 - pow(d / range, 4.0), 0.0, 1.0); att = att * att / (d * d + 1.0);\n"
    "        if (lc.w > 1.5) {\n"
    "            vec4 ld = texelFetch(u_light_tex, base + ivec2(2, 0), 0);\n"
    "            float c = dot(-l, ld.xyz); float outer = ld.w;\n"
    "            att *= smoothstep(outer, mix(outer, 1.0, 0.25), c);\n"
    "        }\n"
    "        color += a3_brdf(s, l, lc.rgb * att);\n"
    "    }\n"
    "    /* hemispheric ambient */\n"
    "    float up = s.normal.y * 0.5 + 0.5;\n"
    "    vec3 amb = mix(u_ground_color, mix(u_sky_horizon, u_sky_color, 0.4), up) * u_ambient;\n"
    "    vec3 f0a = mix(vec3(0.04), s.albedo, s.metallic);\n"
    "    float ndv_a = max(dot(s.normal, s.view_dir), 1e-4);\n"
    "    vec3 fa = f0a + (max(vec3(1.0 - s.roughness), f0a) - f0a) * pow(clamp(1.0 - ndv_a, 0.0, 1.0), 5.0);\n"
    "    vec3 refl = reflect(-s.view_dir, s.normal);\n"
    /* environment reflection: the sky gradient for smooth surfaces, blurred to the ambient term when rough */
    "    vec3 sky_refl = refl.y >= 0.0 ? mix(u_sky_horizon, u_sky_color, pow(clamp(refl.y, 0.0, 1.0), 0.45)) : mix(u_sky_horizon, u_ground_color, clamp(-refl.y * 4.0, 0.0, 1.0));\n"
    "    vec3 env = mix(sky_refl, mix(u_ground_color, u_sky_color, smoothstep(-0.2, 0.4, refl.y)) * u_ambient * 2.0, clamp(s.roughness * 1.6, 0.0, 1.0));\n"
    "    color += (amb * s.albedo * (1.0 - fa) * (1.0 - s.metallic) + env * fa * (1.0 - s.roughness * 0.6)) * s.occlusion;\n"
    "    color += s.emissive + s.albedo * v_params.z;\n"
    "    /* fog (done in the post pass for opaque surfaces) */\n"
    "    if (u_fog_in_post == 0 || s.alpha < 0.999) {\n"
    "        float dist = length(u_camera_pos - s.world_pos);\n"
    "        float fog = 1.0 - exp(-u_fog_density * dist);\n"
    "        color = mix(color, u_fog_color, clamp(fog, 0.0, 1.0));\n"
    "    }\n"
    "    if (any(isnan(color))) color = vec3(0.0);\n"
    "    o_color = vec4(max(color, vec3(0.0)), s.alpha);\n"
    "    o_normal = vec4(s.normal * 0.5 + 0.5, clamp(s.roughness, 0.0, 1.0));\n"
    "}\n";

int a3_shader_surface_line_offset(void) {
    int lines = 0;
    for (const char *p = A3_SHADER_LIT_FS_HEAD; *p; ++p) if (*p == '\n') ++lines;
    return lines;
}

const char *A3_SHADER_SHADOW_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=4) in vec4 i_m0;\n"
    "layout(location=5) in vec4 i_m1;\n"
    "layout(location=6) in vec4 i_m2;\n"
    "layout(location=7) in vec4 i_m3;\n"
    "uniform mat4 u_view_proj;\n"
    "void main() { gl_Position = u_view_proj * mat4(i_m0, i_m1, i_m2, i_m3) * vec4(a_position, 1.0); }\n";

const char *A3_SHADER_SHADOW_FS =
    "void main() {}\n";

const char *A3_SHADER_FULLSCREEN_VS =
    "out vec2 v_uv;\n"
    "void main() {\n"
    "    vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);\n"
    "    v_uv = p;\n"
    "    gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);\n"
    "}\n";

const char *A3_SHADER_SKY_VS =
    "out vec2 v_ndc;\n"
    "void main() {\n"
    "    vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);\n"
    "    v_ndc = p * 2.0 - 1.0;\n"
    "    gl_Position = vec4(v_ndc, 1.0, 1.0);\n"
    "}\n";

const char *A3_SHADER_SKY_FS =
    "in vec2 v_ndc;\n"
    "out vec4 o_color;\n"
    "uniform mat4 u_inv_view_proj;\n"
    "uniform vec3 u_camera_pos;\n"
    "uniform vec3 u_sky_top;\n"
    "uniform vec3 u_sky_horizon;\n"
    "uniform vec3 u_ground_color;\n"
    "uniform vec3 u_sun_dir;\n"
    "uniform vec3 u_sun_color;\n"
    "uniform float u_time;\n"
    "uniform float u_clouds;\n"
    "float hash2(vec2 p) { p = fract(p * vec2(123.34, 456.21)); p += dot(p, p + 45.32); return fract(p.x * p.y); }\n"
    "float hash3(vec3 p) { p = fract(p * vec3(0.1031, 0.1030, 0.0973)); p += dot(p, p.yxz + 33.33); return fract((p.x + p.y) * p.z); }\n"
    "float vnoise(vec2 p) {\n"
    "    vec2 i = floor(p), f = fract(p);\n"
    "    vec2 u = f * f * (3.0 - 2.0 * f);\n"
    "    float a = hash2(i), b = hash2(i + vec2(1.0, 0.0)), c = hash2(i + vec2(0.0, 1.0)), d = hash2(i + vec2(1.0, 1.0));\n"
    "    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);\n"
    "}\n"
    "float fbm(vec2 p) {\n"
    "    float v = 0.0, a = 0.5;\n"
    "    for (int i = 0; i < 6; ++i) { v += a * vnoise(p); p = mat2(1.6, 1.2, -1.2, 1.6) * p; a *= 0.5; }\n"
    "    return v;\n"
    "}\n"
    "void main() {\n"
    "    vec4 far = u_inv_view_proj * vec4(v_ndc, 1.0, 1.0);\n"
    "    vec3 dir = normalize(far.xyz / far.w - u_camera_pos);\n"
    "    float h = dir.y;\n"
    "    vec3 to_sun = -u_sun_dir;\n"
    "    float sun_lum = dot(u_sun_color, vec3(0.2126, 0.7152, 0.0722));\n"
    "    float night = 1.0 - smoothstep(0.06, 0.35, sun_lum);\n"
    "    float mu = dot(dir, to_sun);\n"
    "    float sun_h = to_sun.y;\n"
    "    /* sky gradient: the scene's zenith / horizon colors, with a denser,\n"
    "       brighter band at the horizon (optical depth grows toward it) */\n"
    "    float hp = clamp(h, 0.0, 1.0);\n"
    "    vec3 sky = mix(u_sky_horizon, u_sky_top, pow(hp, 0.45));\n"
    "    sky = mix(sky, u_sky_horizon * 1.12, exp(-hp * 18.0) * 0.5);\n"
    "    /* Rayleigh-like: bluer overhead, brighter on the sun side of the sky */\n"
    "    float ray = 0.75 * (1.0 + mu * mu);\n"
    "    sky *= mix(1.0, 0.85 + 0.2 * ray, 1.0 - night);\n"
    "    /* Mie forward scattering around the sun (Henyey-Greenstein, g = 0.76);\n"
    "       warmer and wider when the sun is low */\n"
    "    float g = 0.76, g2 = g * g;\n"
    "    float hg = (1.0 - g2) / pow(max(1.0 + g2 - 2.0 * g * mu, 1e-4), 1.5) * 0.0796;\n"
    "    float low = 1.0 - smoothstep(0.0, 0.5, sun_h);\n"
    "    vec3 mie_col = mix(u_sun_color, u_sun_color * vec3(1.0, 0.72, 0.5), low);\n"
    "    sky += mie_col * hg * (0.06 + 0.12 * low) * (1.0 - night * 0.8) * smoothstep(-0.15, 0.05, h);\n"
    "    /* horizon glow toward the sun at sunset */\n"
    "    sky += u_sun_color * vec3(1.0, 0.55, 0.3) * pow(max(mu, 0.0), 4.0) * exp(-hp * 7.0) * low * 0.35 * (1.0 - night);\n"
    "    vec3 col = sky;\n"
    "    if (h > 0.0) {\n"
    "        /* stars (fade in at night, fade near the horizon haze) */\n"
    "        if (night > 0.01) {\n"
    "            vec3 sp = dir * 260.0;\n"
    "            vec3 cell = floor(sp);\n"
    "            float r = hash3(cell);\n"
    "            if (r > 0.9965) {\n"
    "                vec3 c = cell + 0.5 + (vec3(hash3(cell + 7.1), hash3(cell + 3.7), hash3(cell + 1.3)) - 0.5) * 0.6;\n"
    "                float d = length(sp - c);\n"
    "                float tw = 0.65 + 0.35 * sin(u_time * (1.5 + r * 40.0) + r * 600.0);\n"
    "                float mag = (r - 0.9965) / 0.0035;\n"
    "                vec3 tint = mix(vec3(0.75, 0.82, 1.0), vec3(1.0, 0.85, 0.7), hash3(cell + 9.9));\n"
    "                col += tint * smoothstep(0.35, 0.0, d) * (0.4 + 2.6 * mag * mag) * tw * night * smoothstep(0.02, 0.25, h);\n"
    "            }\n"
    "        }\n"
    "        /* cloud layer: a slab 1.6 km up, fbm density advected by the wind,\n"
    "           lit by stepping a few samples toward the sun */\n"
    "        if (u_clouds > 0.0 && h > 0.015) {\n"
    "            float t = (1600.0 - u_camera_pos.y) / h;\n"
    "            vec2 wind = vec2(u_time * 6.0, u_time * 2.0);\n"
    "            vec2 p = (u_camera_pos.xz + dir.xz * t + wind) * 0.00055;\n"
    "            float cover = mix(0.62, 0.42, clamp(u_clouds, 0.0, 1.0));\n"
    "            float n = fbm(p);\n"
    "            float dens = smoothstep(cover, cover + 0.2, n);\n"
    "            if (dens > 0.001) {\n"
    "                vec2 sdir = normalize(to_sun.xz + vec2(1e-4)) * 0.035;\n"
    "                float shade = 0.0;\n"
    "                for (int k = 1; k <= 3; ++k) shade += smoothstep(cover, cover + 0.3, fbm(p + sdir * float(k)));\n"
    "                shade /= 3.0;\n"
    "                float lit = exp(-shade * 1.8);\n"
    "                vec3 amb_c = mix(u_sky_top, u_sky_horizon, 0.5) * 0.9;\n"
    "                vec3 sun_c = u_sun_color * (1.0 + low * 0.3) * (0.9 + 1.2 * pow(max(mu, 0.0), 6.0));\n"
    "                vec3 cloud = amb_c * (0.75 + 0.25 * n) + sun_c * lit * 0.95;\n"
    "                /* silver lining toward the sun */\n"
    "                cloud += u_sun_color * pow(max(mu, 0.0), 24.0) * (1.0 - dens) * 2.0;\n"
    "                cloud = mix(cloud, vec3(dot(cloud, vec3(0.33))) * vec3(0.55, 0.55, 0.7) + u_sky_horizon * 0.25, night * 0.7);\n"
    "                float fade = smoothstep(0.015, 0.2, h) * exp(-t * 0.00003);\n"
    "                col = mix(col, cloud, dens * fade * 0.92);\n"
    "            }\n"
    "        }\n"
    "    } else {\n"
    "        col = mix(u_sky_horizon, u_ground_color, clamp(-h * 4.0, 0.0, 1.0));\n"
    "    }\n"
    "    /* the sun disk (limb-darkened) by day, the moon (with maria) at night */\n"
    "    float vis = smoothstep(-0.02, 0.01, h);\n"
    "    if (night < 0.5) {\n"
    "        float cosr = 0.99985;\n"
    "        if (mu > cosr - 0.00008) {\n"
    "            float x = clamp((1.0 - mu) / (1.0 - cosr), 0.0, 1.0);\n"
    "            float limb = 1.0 - 0.6 * (1.0 - sqrt(max(1.0 - x * x, 0.0)));\n"
    "            col += u_sun_color * 22.0 * limb * smoothstep(1.06, 0.94, x) * vis;\n"
    "        }\n"
    "        col += u_sun_color * pow(max(mu, 0.0), 700.0) * 3.0 * vis;\n"
    "    } else {\n"
    "        float cosr = 0.99975;\n"
    "        if (mu > cosr - 0.0001) {\n"
    "            vec3 up = abs(to_sun.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);\n"
    "            vec3 ax = normalize(cross(up, to_sun)), ay = cross(to_sun, ax);\n"
    "            vec2 q = vec2(dot(dir, ax), dot(dir, ay)) / sqrt(1.0 - cosr * cosr);\n"
    "            float rr = length(q);\n"
    "            float maria = fbm(q * 2.5 + 11.0);\n"
    "            vec3 mc = vec3(0.95, 0.95, 1.0) * (0.75 + 0.4 * smoothstep(0.55, 0.35, maria));\n"
    "            col = mix(col, mc * 2.2, smoothstep(1.04, 0.96, rr) * vis);\n"
    "        }\n"
    "        col += vec3(0.6, 0.66, 0.9) * pow(max(mu, 0.0), 180.0) * 0.35 * vis;\n"
    "    }\n"
    "    o_color = vec4(col, 1.0);\n"
    "}\n";

const char *A3_SHADER_TONEMAP_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_hdr;\n"
    "uniform sampler2D u_bloom;\n"
    "uniform float u_bloom_intensity;\n"
    "uniform float u_exposure;\n"
    "uniform float u_vignette;\n"
    "uniform float u_saturation;\n"
    "uniform float u_contrast;\n"
    "uniform vec3 u_tint;\n"
    "uniform sampler2D u_adapt;\n"       /* 1x1: adapted log2 luminance */
    "uniform float u_auto_exposure;\n"   /* 0 = off .. 1 = full eye adaptation */
    "vec3 aces(vec3 x) { return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0); }\n"
    "void main() {\n"
    "    vec3 c = texture(u_hdr, v_uv).rgb + texture(u_bloom, v_uv).rgb * u_bloom_intensity;\n"
    "    float ev = 0.0;\n"
    "    if (u_auto_exposure > 0.0) ev = clamp(-2.4739 - texture(u_adapt, vec2(0.5)).r, -1.5, 1.0) * u_auto_exposure;\n"   /* toward mid grey (log2 0.18) */
    "    c *= u_exposure * exp2(ev) * u_tint;\n"
    /* contrast around mid grey in log space, then saturation */
    "    c = max(c, vec3(0.0));\n"
    "    c = exp2((log2(c + 1e-5) - log2(0.18)) * u_contrast + log2(0.18));\n"
    "    float l = dot(c, vec3(0.2126, 0.7152, 0.0722));\n"
    "    c = max(mix(vec3(l), c, u_saturation), vec3(0.0));\n"
    "    c = aces(c);\n"
    "    c = pow(c, vec3(1.0 / 2.2));\n"
    "    vec2 d = v_uv - 0.5;\n"
    "    c *= 1.0 - u_vignette * dot(d, d) * 1.6;\n"
    /* +-0.5 LSB triangular-ish dither: removes banding in smooth gradients (sky, light falloff) */
    "    float n = fract(sin(dot(gl_FragCoord.xy, vec2(12.9898, 78.233))) * 43758.5453) + fract(sin(dot(gl_FragCoord.xy, vec2(39.3468, 11.1353))) * 24634.6345) - 1.0;\n"
    "    c += n / 255.0;\n"
    "    o_color = vec4(c, dot(c, vec3(0.299, 0.587, 0.114)));\n" /* luma in alpha for FXAA */
    "}\n";

/* ---- screen-space post effects (depth + normal/roughness buffer) ---- */

#define A3_POST_COMMON \
    "in vec2 v_uv;\n" \
    "out vec4 o_color;\n" \
    "uniform sampler2D u_depth;\n" \
    "uniform sampler2D u_normal;\n" \
    "uniform mat4 u_proj;\n" \
    "uniform mat4 u_inv_proj;\n" \
    "uniform mat4 u_view;\n" \
    "uniform int u_zo;\n" \
    "vec3 view_pos(vec2 uv) {\n" \
    "    float d = texture(u_depth, uv).r;\n" \
    "    float z = u_zo != 0 ? d : d * 2.0 - 1.0;\n" \
    "    vec4 p = u_inv_proj * vec4(uv * 2.0 - 1.0, z, 1.0);\n" \
    "    return p.xyz / p.w;\n" \
    "}\n" \
    "vec2 to_uv(vec3 vp) { vec4 c = u_proj * vec4(vp, 1.0); return c.xy / c.w * 0.5 + 0.5; }\n"

/* Screen-space ambient occlusion: 12 samples in a normal-oriented hemisphere. */
const char *A3_SHADER_SSAO_FS =
    A3_POST_COMMON
    "uniform float u_radius;\n"
    "void main() {\n"
    "    float d = texture(u_depth, v_uv).r;\n"
    "    if (d >= 1.0) { o_color = vec4(1.0); return; }\n"
    "    vec3 p = view_pos(v_uv);\n"
    "    vec3 n = normalize(mat3(u_view) * (texture(u_normal, v_uv).xyz * 2.0 - 1.0));\n"
    "    float a = fract(sin(dot(gl_FragCoord.xy, vec2(12.9898, 78.233))) * 43758.5453) * 6.2831853;\n"
    "    vec3 rnd = vec3(cos(a), sin(a), 0.0);\n"
    "    vec3 t = normalize(rnd - n * dot(rnd, n));\n"
    "    vec3 b = cross(n, t);\n"
    "    float radius = u_radius * clamp(-p.z * 0.08, 0.35, 3.0);\n"
    "    float occ = 0.0;\n"
    "    for (int i = 0; i < 12; ++i) {\n"
    "        float fi = float(i) + 0.5;\n"
    "        float r = sqrt(fi / 12.0), phi = fi * 2.39996;\n"
    "        vec3 k = vec3(r * cos(phi), r * sin(phi), sqrt(max(0.0, 1.0 - r * r)));\n"
    "        float sc = mix(0.15, 1.0, (fi / 12.0) * (fi / 12.0));\n"
    "        vec3 sp = p + (t * k.x + b * k.y + n * k.z) * radius * sc;\n"
    "        vec2 suv = to_uv(sp);\n"
    "        if (suv.x < 0.0 || suv.x > 1.0 || suv.y < 0.0 || suv.y > 1.0) continue;\n"
    "        float sz = view_pos(suv).z;\n"
    "        float range = smoothstep(0.0, 1.0, radius / max(abs(p.z - sz), 1e-4));\n"
    "        occ += (sz >= sp.z + 0.02 * radius ? 1.0 : 0.0) * range;\n"
    "    }\n"
    "    o_color = vec4(vec3(1.0 - occ / 12.0), 1.0);\n"
    "}\n";

const char *A3_SHADER_BLUR4_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_src;\n"
    "uniform vec2 u_texel;\n"
    "void main() {\n"
    "    float s = 0.0;\n"
    "    for (int y = -2; y < 2; ++y) for (int x = -2; x < 2; ++x) s += texture(u_src, v_uv + (vec2(x, y) + 0.5) * u_texel).r;\n"
    "    o_color = vec4(vec3(s / 16.0), 1.0);\n"
    "}\n";

/* Composite: ambient occlusion, screen-space reflections, height fog with sun in-scattering. */
const char *A3_SHADER_COMPOSITE_FS =
    A3_POST_COMMON
    "uniform sampler2D u_hdr;\n"
    "uniform sampler2D u_ao;\n"
    "uniform mat4 u_inv_view;\n"
    "uniform vec3 u_camera_pos;\n"
    "uniform float u_ao_strength;\n"
    "uniform float u_ssr_strength;\n"
    "uniform vec3 u_fog_color;\n"
    "uniform float u_fog_density;\n"
    "uniform float u_fog_falloff;\n"
    "uniform vec3 u_sun_dir;\n"
    "uniform vec3 u_sun_color;\n"
    "uniform vec3 u_sun_screen;\n"     /* xy = sun position (uv), z = visibility */
    "uniform float u_shafts;\n"
    /* light shafts: march from the pixel toward the sun on screen and gather
       unoccluded sky near the sun; buildings and trees in between leave dark
       streaks (screen-space, so the sun must be on or near the screen) */
    "vec3 light_shafts() {\n"
    "    if (u_shafts <= 0.0 || u_sun_screen.z <= 0.0) return vec3(0.0);\n"
    "    vec2 d = u_sun_screen.xy - v_uv;\n"
    "    vec2 stepv = d / 32.0;\n"
    "    float dither = fract(sin(dot(gl_FragCoord.xy, vec2(12.9898, 78.233))) * 43758.5453);\n"
    "    vec2 uv = v_uv + stepv * dither;\n"
    "    vec3 acc = vec3(0.0);\n"
    "    float w = 1.0;\n"
    "    for (int i = 0; i < 32; ++i) {\n"
    "        if (uv.x > 0.0 && uv.x < 1.0 && uv.y > 0.0 && uv.y < 1.0) {\n"
    "            float sky = step(1.0, texture(u_depth, uv).r);\n"
    "            float near_sun = exp(-length((uv - u_sun_screen.xy) * vec2(1.6, 1.0)) * 9.0);\n"
    "            acc += min(texture(u_hdr, uv).rgb, vec3(6.0)) * sky * near_sun * w;\n"
    "        }\n"
    "        w *= 0.97;\n"
    "        uv += stepv;\n"
    "    }\n"
    "    return acc / 32.0 * 0.6 * u_shafts * u_sun_screen.z;\n"
    "}\n"
    "void main() {\n"
    "    vec3 col = texture(u_hdr, v_uv).rgb;\n"
    "    float depth = texture(u_depth, v_uv).r;\n"
    "    vec3 shafts = light_shafts();\n"
    "    if (depth >= 1.0) { o_color = vec4(col + shafts, 1.0); return; }\n"
    "    vec3 vp = view_pos(v_uv);\n"
    "    vec3 wp = (u_inv_view * vec4(vp, 1.0)).xyz;\n"
    "    vec4 nr = texture(u_normal, v_uv);\n"
    "    vec3 nw = normalize(nr.xyz * 2.0 - 1.0);\n"
    "    float rough = nr.w;\n"
    "    col *= mix(1.0, texture(u_ao, v_uv).r, u_ao_strength);\n"
    /* reflections: march the reflected ray against the depth buffer */
    "    if (u_ssr_strength > 0.0 && rough < 0.55) {\n"
    "        vec3 nv = normalize(mat3(u_view) * nw);\n"
    "        vec3 vd = normalize(vp);\n"
    "        vec3 r = normalize(reflect(vd, nv));\n"
    "        float fres = 0.04 + 0.96 * pow(clamp(1.0 - dot(-vd, nv), 0.0, 1.0), 5.0);\n"
    "        float stp = max(0.08, -vp.z * 0.02);\n"
    "        vec3 pos = vp + nv * 0.03 * max(1.0, -vp.z * 0.05);\n"
    "        for (int i = 0; i < 48; ++i) {\n"
    "            vec3 prev = pos;\n"
    "            pos += r * stp;\n"
    "            stp *= 1.07;\n"
    "            vec2 suv = to_uv(pos);\n"
    "            if (suv.x < 0.0 || suv.x > 1.0 || suv.y < 0.0 || suv.y > 1.0 || pos.z > -0.05) break;\n"
    "            float sz = view_pos(suv).z;\n"
    "            float diff = sz - pos.z;\n"
    "            if (diff > 0.0 && diff < stp * 2.5 + 0.1) {\n"
    "                vec3 a = prev, b = pos;\n"
    "                for (int j = 0; j < 5; ++j) { vec3 m = (a + b) * 0.5; if (view_pos(to_uv(m)).z - m.z > 0.0) b = m; else a = m; }\n"
    "                vec2 huv = to_uv(b);\n"
    "                if (texture(u_depth, huv).r >= 1.0) break;\n"
    "                vec2 edge = smoothstep(vec2(0.0), vec2(0.08), huv) * (1.0 - smoothstep(vec2(0.92), vec2(1.0), huv));\n"
    "                float fade = edge.x * edge.y * (1.0 - float(i) / 48.0) * (1.0 - rough / 0.55);\n"
    "                col = mix(col, texture(u_hdr, huv).rgb, clamp(fres * fade * u_ssr_strength, 0.0, 1.0));\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    /* exponential height fog, brighter toward the sun */
    "    vec3 ray = wp - u_camera_pos;\n"
    "    float dist = length(ray);\n"
    "    float fog;\n"
    "    if (u_fog_falloff > 1e-4) {\n"
    "        float dy = ray.y * u_fog_falloff;\n"
    "        float line = abs(dy) > 1e-4 ? (1.0 - exp(-dy)) / dy : 1.0;\n"
    "        fog = 1.0 - exp(-u_fog_density * exp(-u_camera_pos.y * u_fog_falloff) * dist * line);\n"
    "    } else fog = 1.0 - exp(-u_fog_density * dist);\n"
    "    float sun = pow(max(dot(ray / max(dist, 1e-4), -u_sun_dir), 0.0), 8.0);\n"
    "    vec3 fc = u_fog_color + u_sun_color * sun * 0.25;\n"
    "    col = mix(col, fc, clamp(fog, 0.0, 1.0));\n"
    "    o_color = vec4(col + shafts, 1.0);\n"
    "}\n";

/* Auto exposure: log luminance of the scene at 64x64, box-averaged down to
 * 1x1, then an adaptation step (the eye adjusts faster to light than to dark). */
const char *A3_SHADER_LUM_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_src;\n"
    "uniform vec2 u_texel;\n"
    "void main() {\n"
    "    float s = 0.0;\n"
    "    for (int y = 0; y < 2; ++y) for (int x = 0; x < 2; ++x) {\n"
    "        vec3 c = texture(u_src, v_uv + (vec2(x, y) - 0.5) * u_texel * 0.5).rgb;\n"
    "        s += log2(max(dot(c, vec3(0.2126, 0.7152, 0.0722)), 1e-4));\n"
    "    }\n"
    "    o_color = vec4(s * 0.25);\n"
    "}\n";

const char *A3_SHADER_AVG4_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_src;\n"
    "uniform vec2 u_src_texel;\n"
    "void main() {\n"
    "    float s = 0.0;\n"
    "    for (int y = 0; y < 4; ++y) for (int x = 0; x < 4; ++x)\n"
    "        s += texture(u_src, v_uv + (vec2(x, y) - 1.5) * u_src_texel).r;\n"
    "    o_color = vec4(s / 16.0);\n"
    "}\n";

const char *A3_SHADER_ADAPT_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_prev;\n"
    "uniform sampler2D u_avg;\n"
    "uniform float u_k_up;\n"
    "uniform float u_k_down;\n"
    "void main() {\n"
    "    float p = texture(u_prev, vec2(0.5)).r, a = texture(u_avg, vec2(0.5)).r;\n"
    "    float k = a > p ? u_k_up : u_k_down;\n"
    "    o_color = vec4(p + (a - p) * k);\n"
    "}\n";

/* Bloom: soft-threshold prefilter + 13-tap downsample; 9-tap tent upsample (added). */
const char *A3_SHADER_BLOOM_DOWN_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_src;\n"
    "uniform vec2 u_texel;\n"
    "uniform float u_threshold;\n"
    "uniform int u_prefilter;\n"
    "vec3 s(vec2 o) { return texture(u_src, v_uv + o * u_texel).rgb; }\n"
    "void main() {\n"
    "    vec3 a = s(vec2(-2, -2)), b = s(vec2(0, -2)), c = s(vec2(2, -2));\n"
    "    vec3 d = s(vec2(-1, -1)), e = s(vec2(1, -1));\n"
    "    vec3 f = s(vec2(-2, 0)), g = s(vec2(0, 0)), h = s(vec2(2, 0));\n"
    "    vec3 i = s(vec2(-1, 1)), j = s(vec2(1, 1));\n"
    "    vec3 k = s(vec2(-2, 2)), l = s(vec2(0, 2)), m = s(vec2(2, 2));\n"
    "    vec3 col = (d + e + i + j) * 0.125 + (a + b + f + g) * 0.03125 + (b + c + g + h) * 0.03125 + (f + g + k + l) * 0.03125 + (g + h + l + m) * 0.03125;\n"
    "    if (u_prefilter != 0) {\n"
    "        if (any(isnan(col)) || any(isinf(col))) col = vec3(0.0);\n"
    "        col = min(col, vec3(24.0));\n"
    "        float br = max(col.r, max(col.g, col.b));\n"
    "        float knee = u_threshold * 0.5;\n"
    "        float soft = clamp(br - u_threshold + knee, 0.0, 2.0 * knee);\n"
    "        soft = soft * soft / (4.0 * knee + 1e-4);\n"
    "        col *= max(soft, br - u_threshold) / max(br, 1e-4);\n"
    "    }\n"
    "    o_color = vec4(col, 1.0);\n"
    "}\n";

const char *A3_SHADER_BLOOM_UP_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_src;\n"
    "uniform vec2 u_texel;\n"
    "vec3 s(vec2 o) { return texture(u_src, v_uv + o * u_texel).rgb; }\n"
    "void main() {\n"
    "    vec3 col = s(vec2(0, 0)) * 4.0 + (s(vec2(-1, 0)) + s(vec2(1, 0)) + s(vec2(0, -1)) + s(vec2(0, 1))) * 2.0\n"
    "             + s(vec2(-1, -1)) + s(vec2(1, -1)) + s(vec2(-1, 1)) + s(vec2(1, 1));\n"
    "    o_color = vec4(col / 16.0, 1.0);\n"
    "}\n";

/* FXAA (quality-lite): edge-directed blur using luma stored in alpha. */
const char *A3_SHADER_FXAA_FS =
    "in vec2 v_uv;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_ldr;\n"
    "uniform vec2 u_texel;\n"
    "void main() {\n"
    "    float lm = texture(u_ldr, v_uv).a;\n"
    "    float ln = texture(u_ldr, v_uv + vec2(0.0, u_texel.y)).a;\n"
    "    float ls = texture(u_ldr, v_uv - vec2(0.0, u_texel.y)).a;\n"
    "    float le = texture(u_ldr, v_uv + vec2(u_texel.x, 0.0)).a;\n"
    "    float lw = texture(u_ldr, v_uv - vec2(u_texel.x, 0.0)).a;\n"
    "    float mn = min(lm, min(min(ln, ls), min(le, lw))), mx = max(lm, max(max(ln, ls), max(le, lw)));\n"
    "    vec3 c = texture(u_ldr, v_uv).rgb;\n"
    "    if (mx - mn < max(0.0312, mx * 0.125)) { o_color = vec4(c, 1.0); return; }\n"
    "    vec2 dir = normalize(vec2(ln - ls, lw - le) + 1e-5) * u_texel;\n"
    "    vec3 a = 0.5 * (texture(u_ldr, v_uv + dir * (1.0/3.0 - 0.5)).rgb + texture(u_ldr, v_uv + dir * (2.0/3.0 - 0.5)).rgb);\n"
    "    vec3 b = a * 0.5 + 0.25 * (texture(u_ldr, v_uv - dir * 0.5).rgb + texture(u_ldr, v_uv + dir * 0.5).rgb);\n"
    "    float lb = dot(b, vec3(0.299, 0.587, 0.114));\n"
    "    o_color = vec4((lb < mn || lb > mx) ? a : b, 1.0);\n"
    "}\n";

const char *A3_SHADER_LINES_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=3) in vec4 a_color;\n"
    "uniform mat4 u_view_proj;\n"
    "out vec4 v_color;\n"
    "void main() { v_color = a_color; gl_Position = u_view_proj * vec4(a_position, 1.0); }\n";

const char *A3_SHADER_LINES_FS =
    "in vec4 v_color;\n"
    "out vec4 o_color;\n"
    "void main() { o_color = v_color; }\n";

/* 2D UI: position in pixels, uv, color. u_mode: 0 = texture rgba, 1 = alpha (font atlas). */
const char *A3_SHADER_UI_VS =
    "layout(location=0) in vec2 a_position;\n"
    "layout(location=2) in vec2 a_uv;\n"
    "layout(location=3) in vec4 a_color;\n"
    "uniform vec2 u_screen;\n"
    "out vec2 v_uv;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    v_uv = a_uv; v_color = a_color;\n"
    "    gl_Position = vec4(a_position.x / u_screen.x * 2.0 - 1.0, 1.0 - a_position.y / u_screen.y * 2.0, 0.0, 1.0);\n"
    "}\n";

const char *A3_SHADER_UI_FS =
    "in vec2 v_uv;\n"
    "in vec4 v_color;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_tex;\n"
    "uniform int u_mode;\n"
    "void main() {\n"
    "    vec4 t = texture(u_tex, v_uv);\n"
    "    if (u_mode == 1) o_color = vec4(v_color.rgb, v_color.a * t.r);\n"
    "    else o_color = v_color * t;\n"
    "}\n";

/* Editor ground grid, drawn as a large quad with analytic anti-aliased lines. */
const char *A3_SHADER_GRID_VS =
    "layout(location=0) in vec3 a_position;\n"
    "uniform mat4 u_view_proj;\n"
    "uniform vec3 u_camera_pos;\n"
    "out vec3 v_world;\n"
    "void main() {\n"
    "    vec3 p = a_position * 500.0 + vec3(u_camera_pos.x, 0.0, u_camera_pos.z);\n"
    "    v_world = p;\n"
    "    gl_Position = u_view_proj * vec4(p, 1.0);\n"
    "}\n";

const char *A3_SHADER_GRID_FS =
    "in vec3 v_world;\n"
    "out vec4 o_color;\n"
    "uniform vec3 u_camera_pos;\n"
    "float grid(vec2 p, float scale) {\n"
    "    vec2 c = p / scale; vec2 d = fwidth(c);\n"
    "    vec2 g = abs(fract(c - 0.5) - 0.5) / d;\n"
    "    return 1.0 - min(min(g.x, g.y), 1.0);\n"
    "}\n"
    "void main() {\n"
    "    float dist = length(v_world.xz - u_camera_pos.xz);\n"
    "    float fade = 1.0 - smoothstep(30.0, 180.0, dist);\n"
    "    float g1 = grid(v_world.xz, 1.0) * 0.35, g10 = grid(v_world.xz, 10.0) * 0.6;\n"
    "    float a = max(g1, g10) * fade;\n"
    "    vec3 col = vec3(0.55);\n"
    "    if (abs(v_world.z) < fwidth(v_world.z) * 1.5) { col = vec3(0.9, 0.25, 0.25); a = fade; }\n"
    "    if (abs(v_world.x) < fwidth(v_world.x) * 1.5) { col = vec3(0.25, 0.45, 0.95); a = fade; }\n"
    "    if (a < 0.01) discard;\n"
    "    o_color = vec4(col, a);\n"
    "}\n";

/* Camera-facing particles: per-instance position/size (loc 4), color (loc 8). */
const char *A3_SHADER_PARTICLE_VS =
    "layout(location=0) in vec3 a_position;\n"
    "layout(location=2) in vec2 a_uv;\n"
    "layout(location=4) in vec4 i_pos_size;\n"
    "layout(location=8) in vec4 i_color;\n"
    "uniform mat4 u_view_proj;\n"
    "uniform vec3 u_cam_right;\n"
    "uniform vec3 u_cam_up;\n"
    "out vec2 v_uv;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec3 p = i_pos_size.xyz + (u_cam_right * a_position.x + u_cam_up * a_position.y) * i_pos_size.w;\n"
    "    v_uv = a_uv; v_color = i_color;\n"
    "    gl_Position = u_view_proj * vec4(p, 1.0);\n"
    "}\n";

const char *A3_SHADER_PARTICLE_FS =
    "in vec2 v_uv;\n"
    "in vec4 v_color;\n"
    "out vec4 o_color;\n"
    "uniform sampler2D u_tex;\n"
    "uniform int u_has_texture;\n"
    "void main() {\n"
    "    vec2 d = v_uv * 2.0 - 1.0;\n"
    "    float soft = clamp(1.0 - dot(d, d), 0.0, 1.0);\n"
    "    vec4 c = v_color;\n"
    "    if (u_has_texture != 0) c *= texture(u_tex, v_uv); else c.a *= soft * soft;\n"
    "    if (c.a < 0.003) discard;\n"
    "    o_color = c;\n"
    "}\n";
