#!/usr/bin/env python3
"""Generates engine/ui/a3_font_data.c: an embedded glyph atlas for the editor
and in-game UI, rasterized from DejaVu fonts (Bitstream Vera license, see
docs/THIRD_PARTY.md). Run only when changing fonts; output is committed."""
from PIL import Image, ImageFont
import sys

SANS = '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'
BOLD = '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'
MONO = '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'
FACES = [  # (enum name, file, pixel size)
    ('A3_FONT_UI', SANS, 15), ('A3_FONT_UI_LARGE', SANS, 18), ('A3_FONT_TITLE', SANS, 26),
    ('A3_FONT_UI_BOLD', BOLD, 15), ('A3_FONT_HEADING', BOLD, 18),
    ('A3_FONT_MONO', MONO, 14), ('A3_FONT_MONO_LARGE', MONO, 17),
]
ICONS = [0x25B6,0x25A0,0x25CF,0x25CB,0x2713,0x2715,0x2699,0x2600,0x2605,0x25BC,0x25BA,0x25C0,0x25B2,0x25B8,0x25BE,
         0x2302,0x270E,0x2630,0x2295,0x229E,0x21BB,0x21B6,0x21B7,0x271A,0x26A0,0x25A3,0x25C6,0x25C7,0x266A,0x2601,
         0x26A1,0x2016,0x2192,0x2190,0x2191,0x2193,0x2194,0x2195,0x21C4,0x2022,0x2026,0x2261,0x2318,0x25EF,0x2764,
         0x263C,0x2609,0x2B21,0x25A1,0x25AB,0x2B24,0x2750,0x2B1A]
CODEPOINTS = list(range(32, 127)) + list(range(160, 256)) + ICONS

glyphs = []  # (face_index, cp, image, xoff, yoff, advance)
faces_meta = []
for fi, (name, path, size) in enumerate(FACES):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    first = len(glyphs)
    for cp in CODEPOINTS:
        ch = chr(cp)
        try:
            bbox = font.getbbox(ch)  # relative to origin at top of ascent
        except Exception:
            continue
        adv = font.getlength(ch)
        if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append((fi, cp, None, 0, 0, adv))
            continue
        w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
        img = Image.new('L', (w, h), 0)
        from PIL import ImageDraw
        ImageDraw.Draw(img).text((-bbox[0], -bbox[1]), ch, font=font, fill=255)
        glyphs.append((fi, cp, img, bbox[0], bbox[1], adv))
    faces_meta.append((name, size, ascent, descent, first, len(glyphs) - first))

# shelf packing
W = 1024
order = sorted([i for i, g in enumerate(glyphs) if g[2] is not None], key=lambda i: -glyphs[i][2].size[1])
pos = {}
x, y, shelf_h = 1, 4, 0   # (0..3, 0..3) reserved as a white block for solid fills
for i in order:
    w, h = glyphs[i][2].size
    if x + w + 1 > W:
        x = 1; y += shelf_h + 1; shelf_h = 0
    pos[i] = (x, y)
    x += w + 1
    shelf_h = max(shelf_h, h)
H = 1
while H < y + shelf_h + 1: H *= 2
atlas = Image.new('L', (W, H), 0)
for yy in range(4):
    for xx in range(4):
        atlas.putpixel((xx, yy), 255)
for i, (px, py) in pos.items():
    atlas.paste(glyphs[i][2], (px, py))
data = atlas.tobytes()

# RLE: b < 128 -> (b+1) literal bytes follow; b >= 128 -> run of (b-127) zero bytes
out = bytearray()
i = 0
n = len(data)
while i < n:
    if data[i] == 0:
        j = i
        while j < n and data[j] == 0 and j - i < 128: j += 1
        out.append(127 + (j - i)); i = j
    else:
        j = i
        while j < n and data[j] != 0 and j - i < 128: j += 1
        out.append(j - i - 1); out += data[i:j]; i = j

with open('engine/ui/a3_font_data.c', 'w') as f:
    f.write('/* Generated by tools/gen_font_atlas.py - do not edit.\n')
    f.write(' * Glyphs rasterized from DejaVu Sans / Sans Bold / Sans Mono\n')
    f.write(' * (Bitstream Vera license; see docs/THIRD_PARTY.md). */\n')
    f.write('#include "a3_font.h"\n\n')
    f.write(f'const i32 a3_font_atlas_width = {W};\nconst i32 a3_font_atlas_height = {H};\n')
    f.write('const A3FontFaceData a3_font_faces[A3_FONT_COUNT] = {\n')
    for (name, size, asc, desc, first, count) in faces_meta:
        f.write(f'    {{ {size}, {asc}, {desc}, {first}, {count} }}, /* {name} */\n')
    f.write('};\n')
    f.write(f'const u32 a3_font_glyph_count = {len(glyphs)};\n')
    f.write('const A3GlyphData a3_font_glyphs[] = {\n')
    for i, (fi, cp, img, xo, yo, adv) in enumerate(glyphs):
        if img is None:
            f.write(f'    {{ {cp}, 0, 0, 0, 0, 0, 0, {adv:.2f}f }},\n')
        else:
            px, py = pos[i]
            f.write(f'    {{ {cp}, {px}, {py}, {img.size[0]}, {img.size[1]}, {xo}, {yo}, {adv:.2f}f }},\n')
    f.write('};\n')
    f.write(f'const u32 a3_font_atlas_rle_size = {len(out)};\n')
    f.write('const u8 a3_font_atlas_rle[] = {\n')
    for k in range(0, len(out), 24):
        f.write('    ' + ','.join(str(b) for b in out[k:k+24]) + ',\n')
    f.write('};\n')
print(f'atlas {W}x{H}, {len(glyphs)} glyphs, rle {len(out)} bytes (raw {len(data)})', file=sys.stderr)
